// <auto-generated />
namespace BITCollege_GiangHuynh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClassSupport_NextRegistrationNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassSupport_NextRegistrationNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201909240132287_ClassSupport_NextRegistrationNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
