//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITCollegeSite.SRCollegeRegistration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRCollegeRegistration.ICollegeRegistration")]
    public interface ICollegeRegistration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollegeRegistration/dropCourse", ReplyAction="http://tempuri.org/ICollegeRegistration/dropCourseResponse")]
        bool dropCourse(int registrationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollegeRegistration/dropCourse", ReplyAction="http://tempuri.org/ICollegeRegistration/dropCourseResponse")]
        System.Threading.Tasks.Task<bool> dropCourseAsync(int registrationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollegeRegistration/registerCourse", ReplyAction="http://tempuri.org/ICollegeRegistration/registerCourseResponse")]
        int registerCourse(int studentId, int courseId, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollegeRegistration/registerCourse", ReplyAction="http://tempuri.org/ICollegeRegistration/registerCourseResponse")]
        System.Threading.Tasks.Task<int> registerCourseAsync(int studentId, int courseId, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollegeRegistration/updateGrade", ReplyAction="http://tempuri.org/ICollegeRegistration/updateGradeResponse")]
        void updateGrade(double grade, int registrationId, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollegeRegistration/updateGrade", ReplyAction="http://tempuri.org/ICollegeRegistration/updateGradeResponse")]
        System.Threading.Tasks.Task updateGradeAsync(double grade, int registrationId, string notes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICollegeRegistrationChannel : BITCollegeSite.SRCollegeRegistration.ICollegeRegistration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollegeRegistrationClient : System.ServiceModel.ClientBase<BITCollegeSite.SRCollegeRegistration.ICollegeRegistration>, BITCollegeSite.SRCollegeRegistration.ICollegeRegistration {
        
        public CollegeRegistrationClient() {
        }
        
        public CollegeRegistrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollegeRegistrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollegeRegistrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollegeRegistrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool dropCourse(int registrationId) {
            return base.Channel.dropCourse(registrationId);
        }
        
        public System.Threading.Tasks.Task<bool> dropCourseAsync(int registrationId) {
            return base.Channel.dropCourseAsync(registrationId);
        }
        
        public int registerCourse(int studentId, int courseId, string notes) {
            return base.Channel.registerCourse(studentId, courseId, notes);
        }
        
        public System.Threading.Tasks.Task<int> registerCourseAsync(int studentId, int courseId, string notes) {
            return base.Channel.registerCourseAsync(studentId, courseId, notes);
        }
        
        public void updateGrade(double grade, int registrationId, string notes) {
            base.Channel.updateGrade(grade, registrationId, notes);
        }
        
        public System.Threading.Tasks.Task updateGradeAsync(double grade, int registrationId, string notes) {
            return base.Channel.updateGradeAsync(grade, registrationId, notes);
        }
    }
}
