//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITCollege_GiangHuynh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BITCollege_GiangHuynh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ================================================
        ///-- Template generated from Template Explorer using:
        ///-- Create Procedure (New Menu).SQL
        ///--
        ///-- Use the Specify Values for Template Parameters 
        ///-- command (Ctrl-Shift-M) to fill in the parameter 
        ///-- values below.
        ///--
        ///-- This block of comments will not be included in
        ///-- the definition of the procedure.
        ///-- ================================================
        ///CREATE PROCEDURE [dbo].[next_number]
        ///	-- Add the parameters for the stored procedure here
        ///	@Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string create_next_number {
            get {
                return ResourceManager.GetString("create_next_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ================================================
        ///-- Template generated from Template Explorer using:
        ///-- Create Procedure (New Menu).SQL
        ///--
        ///-- Use the Specify Values for Template Parameters 
        ///-- command (Ctrl-Shift-M) to fill in the parameter 
        ///-- values below.
        ///--
        ///-- This block of comments will not be included in
        ///-- the definition of the procedure.
        ///-- ================================================
        ///DROP PROCEDURE [dbo].[next_number]
        ///.
        /// </summary>
        internal static string drop_next_number {
            get {
                return ResourceManager.GetString("drop_next_number", resourceCulture);
            }
        }
    }
}
